// One-time generator: builds ../data/names.js
// Source for Arabic/transliteration/order: cross-checked against myislam.org's 99 Names table (2026).
// English & Swahili glosses below are original short paraphrases, not copied from any source.
import fs from "fs";

const rows = [
[1,"Ar-Rahman","الرَّحْمَنُ","The Most Compassionate","The One whose mercy embraces all creation without exception.","Mwingi wa Rehema","Yeye ambaye ni mwenye huruma kwa viumbe vyote katika ulimwengu huu."],
[2,"Ar-Rahim","الرَّحِيمُ","The Most Merciful","The One who shows special, lasting mercy to the believers.","Mwenye Kurehemu","Yeye ambaye ni mwenye huruma hasa kwa waumini katika maisha ya baadaye."],
[3,"Al-Malik","الْمَلِكُ","The King","The Sovereign who owns and rules all that exists.","Mfalme","Mmiliki na Mtawala wa vyote vilivyopo."],
[4,"Al-Quddus","الْقُدُّوسُ","The Most Holy","The One utterly free from every flaw or imperfection.","Mtakatifu","Yeye aliye safi na mbali na dosari zote."],
[5,"As-Salam","السَّلاَمُ","The Source of Peace","The One free of all defect, who grants safety and peace.","Chanzo cha Amani","Yeye asiye na upungufu, mpaji wa amani na salama."],
[6,"Al-Mu'min","الْمُؤْمِنُ","The Granter of Security","The One who gives safety and confirms the truth for believers.","Mpaji wa Amani","Yeye anayewapa waumini uhakika na usalama."],
[7,"Al-Muhaymin","الْمُهَيْمِنُ","The Guardian","The One who watches over and protects all creation.","Mlinzi Mkuu","Yeye anayesimamia na kulinda viumbe vyote."],
[8,"Al-Aziz","الْعَزِيزُ","The Almighty","The One whose strength and honor can never be overcome.","Mwenye Enzi","Yeye asiyeshindwa na yeyote."],
[9,"Al-Jabbar","الْجَبَّارُ","The Compeller","The One who mends what is broken and enforces His will.","Mlazimishaji","Yeye anayerekebisha na kutekeleza matakwa yake bila kupingwa."],
[10,"Al-Mutakabbir","الْمُتَكَبِّر","The Supremely Great","The One who alone deserves greatness and majesty.","Mkuu wa Enzi","Yeye pekee anayestahili ukuu na fahari."],
[11,"Al-Khaliq","الْخَالِقُ","The Creator","The One who brings all things into existence from nothing.","Muumbaji","Yeye aletaye vitu vyote kuwepo kutoka hali ya kutokuwepo."],
[12,"Al-Bari'","الْبَارِئُ","The Maker","The One who designs and originates creation in perfect order.","Mwenye Kubuni Uumbaji","Yeye anayepanga uumbaji kwa mpangilio kamili."],
[13,"Al-Musawwir","الْمُصَوِّرُ","The Fashioner","The One who gives every creature its unique form.","Mtengeneza Sura","Yeye anayeumba kila kiumbe kwa umbo lake la pekee."],
[14,"Al-Ghaffar","الْغَفَّارُ","The Ever-Forgiving","The One who forgives sins again and again.","Mwingi wa Msamaha","Yeye anayesamehe dhambi mara kwa mara."],
[15,"Al-Qahhar","الْقَهَّارُ","The Subduer","The One whose power overcomes all things without resistance.","Mshindaji","Yeye ambaye nguvu zake hazizuiliwi na chochote."],
[16,"Al-Wahhab","الْوَهَّابُ","The Bestower","The One who gives generously without expecting anything back.","Mtoaji Mkuu","Yeye anayetoa kwa ukarimu bila kutegemea malipo."],
[17,"Ar-Razzaq","الرَّزَّاقُ","The Provider","The One who supplies sustenance to every living being.","Mruzuku","Yeye anayewapa riziki viumbe vyote."],
[18,"Al-Fattah","الْفَتَّاحُ","The Opener","The One who opens the way and settles every matter with justice.","Mfunguzi","Yeye anayefungua njia na kuamua mambo kwa haki."],
[19,"Al-'Alim","اَلْعَلِيْمُ","The All-Knowing","The One whose knowledge encompasses everything, seen and unseen.","Mjuzi wa Yote","Yeye anayejua kila kitu, dhahiri na siri."],
[20,"Al-Qabid","الْقَابِضُ","The Withholder","The One who restricts provision and life by His wisdom.","Mpunguzaji","Yeye anayepunguza riziki kwa hekima yake."],
[21,"Al-Basit","الْبَاسِطُ","The Extender","The One who expands provision and ease for whoever He wills.","Mpanuzi","Yeye anayekunjua riziki na wasaa kwa amtakaye."],
[22,"Al-Khafid","الْخَافِضُ","The Abaser","The One who humbles the arrogant and lowers whoever He wills.","Mshushaji","Yeye anayemshusha mwenye kiburi na amtakaye."],
[23,"Ar-Rafi'","الرَّافِعُ","The Exalter","The One who raises in honor whoever He wills.","Mwinuaji","Yeye anayemwinua na kumtukuza amtakaye."],
[24,"Al-Mu'izz","الْمُعِزُّ","The Bestower of Honor","The One who grants dignity and honor to whoever He wills.","Mpaji wa Heshima","Yeye anayempa heshima amtakaye."],
[25,"Al-Mudhill","ٱلْمُذِلُّ","The Humiliator","The One who withdraws honor from whoever He wills.","Mdhalilishaji","Yeye anayeondoa heshima kwa amtakaye."],
[26,"As-Sami'","السَّمِيعُ","The All-Hearing","The One who hears every sound, spoken or silent.","Msikizi wa Yote","Yeye anayesikia kila sauti, iliyotamkwa au ya ndani ya moyo."],
[27,"Al-Basir","الْبَصِيرُ","The All-Seeing","The One who sees all things, however hidden.","Mwenye Kuona Yote","Yeye anayeona kila kitu, hata kilichofichika."],
[28,"Al-Hakam","الْحَكَمُ","The Judge","The One whose ruling is final and perfectly just.","Hakimu","Yeye ambaye hukumu yake ni ya mwisho na ya haki kamili."],
[29,"Al-'Adl","الْعَدْلُ","The Utterly Just","The One who is never unfair in any matter.","Mwenye Haki","Yeye asiyefanya dhuluma katika jambo lolote."],
[30,"Al-Latif","اللَّطِيفُ","The Subtle One","The One who is gentle and aware of the finest details.","Mpole wa Ndani","Yeye mpole anayejua mambo madogo yaliyofichika."],
[31,"Al-Khabir","الْخَبِيرُ","The All-Aware","The One who knows the true reality of every matter.","Mjuzi wa Siri","Yeye anayejua uhalisia wa kila jambo."],
[32,"Al-Halim","الْحَلِيمُ","The Forbearing","The One who delays punishment, giving room to repent.","Mvumilivu","Yeye anayechelewesha adhabu ili kutoa nafasi ya toba."],
[33,"Al-'Azim","الْعَظِيمُ","The Magnificent","The One of supreme greatness beyond all comparison.","Mkuu wa Utukufu","Yeye mwenye ukuu usio na kifani."],
[34,"Al-Ghafur","الْغَفُور","The Forgiving","The One who forgives abundantly and often.","Mwenye Kusamehe Sana","Yeye anayesamehe kwa wingi."],
[35,"Ash-Shakur","الشَّكُورُ","The Appreciative","The One who rewards good deeds generously, however small.","Mshukuru","Yeye anayelipa vyema hata tendo dogo jema."],
[36,"Al-'Aliyy","الْعَلِيُّ","The Most High","The One elevated far above all creation.","Aliye Juu Zaidi","Yeye aliyeinuka juu ya viumbe vyote."],
[37,"Al-Kabir","الْكَبِيرُ","The Greatest","The One greater in status than everything that exists.","Mkubwa","Yeye aliye mkubwa kuliko vyote vilivyopo."],
[38,"Al-Hafiz","الْحَفِيظُ","The Preserver","The One who safeguards His creation and their deeds.","Mlinzi wa Vyote","Yeye anayehifadhi viumbe na matendo yao."],
[39,"Al-Muqit","المُقيِت","The Sustainer","The One who provides strength and nourishment to all.","Mlishaji","Yeye anayetoa nguvu na riziki kwa vyote."],
[40,"Al-Hasib","الْحسِيبُ","The Reckoner","The One who accounts fully for every deed.","Mhesabu","Yeye anayehesabu kila tendo kikamilifu."],
[41,"Al-Jalil","الْجَلِيلُ","The Majestic","The One possessing supreme greatness and grandeur.","Mtukufu","Yeye mwenye ukuu na fahari kubwa."],
[42,"Al-Karim","الْكَرِيمُ","The Generous","The One whose giving is noble and never runs short.","Mkarimu","Yeye ambaye ukarimu wake hauishi."],
[43,"Ar-Raqib","الرَّقِيبُ","The Watchful","The One who observes all things at every moment.","Mwangalizi","Yeye anayeangalia kila kitu kila wakati."],
[44,"Al-Mujib","ٱلْمُجِيبُ","The Responsive","The One who answers the call of those in need.","Mwitikiaji","Yeye anayejibu dua za wenye shida."],
[45,"Al-Wasi'","الْوَاسِعُ","The All-Encompassing","The One whose knowledge and mercy embrace everything without limit.","Mwenye Wasaa","Yeye ambaye elimu na rehema yake hazina mipaka."],
[46,"Al-Hakim","الْحَكِيمُ","The Wise","The One who places everything precisely where it belongs.","Mwenye Hekima","Yeye anayeweka kila kitu mahali panapofaa."],
[47,"Al-Wadud","الْوَدُودُ","The Loving","The One who loves His righteous servants and is loved by them.","Mpenzi","Yeye anayewapenda watumishi wema na wao wanampenda."],
[48,"Al-Majid","الْمَجِيدُ","The Glorious","The One of perfect honor, generosity and majesty.","Mtukufu wa Enzi","Yeye mwenye heshima, ukarimu na fahari kamili."],
[49,"Al-Ba'ith","الْبَاعِثُ","The Resurrector","The One who will raise all creation back to life.","Mfufuaji","Yeye atakayewafufua viumbe vyote."],
[50,"Ash-Shahid","الشَّهِيدُ","The Witness","The One from whom nothing is ever hidden.","Shahidi","Yeye ambaye hakuna jambo linalofichika kwake."],
[51,"Al-Haqq","الْحَقُ","The Truth","The One whose existence and promise are absolutely real.","Ukweli","Yeye ambaye kuwepo kwake na ahadi yake ni za kweli kabisa."],
[52,"Al-Wakil","الْوَكِيلُ","The Trustee","The One who can be fully relied upon in every affair.","Mtegemewa","Yeye ambaye anaweza kutegemewa kikamilifu katika kila jambo."],
[53,"Al-Qawiyy","الْقَوِيُ","The Most Strong","The One whose power is complete and unshakable.","Mwenye Nguvu Kamili","Yeye ambaye nguvu zake hazitikisiki."],
[54,"Al-Matin","الْمَتِينُ","The Firm One","The One whose strength never tires or weakens.","Imara","Yeye ambaye nguvu zake haziishi wala hazichoki."],
[55,"Al-Waliyy","الْوَلِيُّ","The Protecting Friend","The One who supports and befriends the believers.","Rafiki Mlinzi","Yeye anayewasaidia na kuwa rafiki wa waumini."],
[56,"Al-Hamid","الْحَمِيدُ","The Praiseworthy","The One deserving of all praise in every state.","Wa Kusifiwa","Yeye anayestahili sifa katika hali zote."],
[57,"Al-Muhsi","الْمُحْصِي","The Reckoner of All","The One who keeps count of everything without error.","Mhesabu Kila Kitu","Yeye anayejua idadi ya kila kitu bila kukosea."],
[58,"Al-Mubdi'","الْمُبْدِئُ","The Originator","The One who began creation without any prior example.","Mwanzilishi","Yeye aliyeanzisha uumbaji bila mfano wa awali."],
[59,"Al-Mu'id","ٱلْمُعِيدُ","The Restorer","The One who will bring creation back after death.","Mrejeshaji","Yeye atakayewarejesha viumbe baada ya kifo."],
[60,"Al-Muhyi","الْمُحْيِي","The Giver of Life","The One who brings the lifeless to life.","Mpaji wa Uhai","Yeye anayeleta uhai kwa kisichokuwa na uhai."],
[61,"Al-Mumit","اَلْمُمِيتُ","The Bringer of Death","The One who causes every living being to die.","Mletaji wa Mauti","Yeye anayesababisha kila kiumbe hai kufa."],
[62,"Al-Hayy","الْحَيُّ","The Ever-Living","The One whose life never began and will never end.","Aliye Hai Milele","Yeye ambaye uhai wake hauna mwanzo wala mwisho."],
[63,"Al-Qayyum","الْقَيُّومُ","The Self-Subsisting Sustainer","The One who sustains all existence while needing nothing.","Msimamizi Mkuu","Yeye anayesimamisha viumbe vyote bila kuhitaji chochote."],
[64,"Al-Wajid","الْوَاجِدُ","The Finder","The One who lacks nothing and finds whatever He wills.","Tajiri Asiye na Uhitaji","Yeye asiyekosa kitu na apatae atakalo."],
[65,"Al-Majid","الْمَاجِدُ","The Noble One","The One of magnificent honor and generosity.","Mwenye Utukufu","Yeye mwenye heshima na ukarimu mkubwa."],
[66,"Al-Wahid","الْواحِدُ","The One","The One without partner or equal.","Wa Pekee","Yeye asiye na mshirika wala mfano."],
[67,"Al-Ahad","اَلاَحَدُ","The Unique","The One indivisible in His essence.","Mmoja Asiyegawanyika","Yeye asiyegawanyika katika dhati yake."],
[68,"As-Samad","الصَّمَدُ","The Eternal Refuge","The One to whom all creation turns in need.","Kimbilio la Milele","Yeye ambaye viumbe vyote vinamrejea wanapohitaji."],
[69,"Al-Qadir","الْقَادِرُ","The All-Powerful","The One capable of doing whatever He wills.","Mwenye Uwezo","Yeye mwenye uwezo wa kufanya atakalo."],
[70,"Al-Muqtadir","الْمُقْتَدِرُ","The All-Authoritative","The One whose power nothing can restrain.","Mwenye Mamlaka Kamili","Yeye ambaye hakuna kizuizi kwa uwezo wake."],
[71,"Al-Muqaddim","الْمُقَدِّمُ","The Expediter","The One who brings forward whatever and whoever He wills.","Mtangulizaji","Yeye anayetanguliza atakalo na amtakaye."],
[72,"Al-Mu'akhkhir","الْمُؤَخِّرُ","The Delayer","The One who postpones whatever and whoever He wills.","Mcheleweshaji","Yeye anayechelewesha atakalo na amtakaye."],
[73,"Al-Awwal","الأوَّلُ","The First","The One who existed before anything else.","Wa Kwanza","Yeye aliyekuwepo kabla ya kila kitu."],
[74,"Al-Akhir","الآخِرُ","The Last","The One who remains after everything else ends.","Wa Mwisho","Yeye atakayebaki baada ya kila kitu kutoweka."],
[75,"Az-Zahir","الظَّاهِرُ","The Manifest","The One whose existence is evident through all creation.","Dhahiri","Yeye ambaye kuwepo kwake kunathibitika kupitia viumbe vyote."],
[76,"Al-Batin","الْبَاطِنُ","The Hidden","The One whose true essence is beyond human perception.","Aliyefichika","Yeye ambaye dhati yake haiwezi kufikiwa na akili za binadamu."],
[77,"Al-Wali","الْوَالِي","The Governor","The One who manages and administers all affairs.","Msimamizi","Yeye anayesimamia na kuendesha mambo yote."],
[78,"Al-Muta'ali","الْمُتَعَالِي","The Most Exalted","The One far above any resemblance to creation.","Aliyetukuka Zaidi","Yeye aliye mbali na kufanana na viumbe."],
[79,"Al-Barr","الْبَرُّ","The Source of Goodness","The One whose kindness toward His creation is abundant.","Chanzo cha Wema","Yeye ambaye wema wake kwa viumbe ni mwingi."],
[80,"At-Tawwab","التَّوَابُ","The Ever-Accepting of Repentance","The One who repeatedly turns to forgive those who repent.","Mpokea Toba","Yeye anayewasamehe mara kwa mara wanaotubu."],
[81,"Al-Muntaqim","الْمُنْتَقِمُ","The Avenger","The One who justly punishes persistent wrongdoing.","Mlipiza kwa Haki","Yeye anayeadhibu kwa haki uovu unaoendelea."],
[82,"Al-'Afuww","العَفُوُ","The Pardoner","The One who erases sins entirely for those who seek forgiveness.","Mwenye Kufuta Dhambi","Yeye anayefuta kabisa dhambi za wanaotaka msamaha."],
[83,"Ar-Ra'uf","الرَّؤُوفُ","The Most Kind","The One whose gentleness and tenderness are boundless.","Mpole wa Huruma","Yeye ambaye upole na huruma yake haina kikomo."],
[84,"Malik-ul-Mulk","مَالِكُ ٱلْمُلْكُ","Owner of All Sovereignty","The One who controls dominion, giving and taking it as He wills.","Mmiliki wa Ufalme Wote","Yeye anayemiliki na kugawa utawala kwa amtakaye."],
[85,"Dhul-Jalali-wal-Ikram","ذُوالْجَلاَلِ وَالإكْرَامِ","Lord of Majesty and Generosity","The One possessing both supreme greatness and boundless generosity.","Mwenye Utukufu na Ukarimu","Yeye mwenye ukuu na ukarimu usio na mipaka."],
[86,"Al-Muqsit","الْمُقْسِطُ","The Equitable","The One who always acts and judges with fairness.","Mwenye Usawa","Yeye anayetenda na kuhukumu kwa usawa daima."],
[87,"Al-Jami'","الْجَامِعُ","The Gatherer","The One who will bring all creation together on the Day of Judgment.","Mkusanyaji","Yeye atakayewakusanya viumbe vyote Siku ya Kiyama."],
[88,"Al-Ghaniyy","ٱلْغَنيُّ","The Self-Sufficient","The One who needs nothing from His creation.","Asiyehitaji","Yeye asiyehitaji chochote kutoka kwa viumbe."],
[89,"Al-Mughni","ٱلْمُغْنِيُّ","The Enricher","The One who frees His creation from need and want.","Mtajirisha","Yeye anayewaondolea viumbe uhitaji."],
[90,"Al-Mani'","اَلْمَانِعُ","The Preventer","The One who withholds harm or hardship from whoever He wills.","Mzuiaji","Yeye anayemzuilia madhara amtakaye."],
[91,"Ad-Darr","الضَّارَ","The Distressor","The One who allows harm by His wisdom and justice, as a consequence, never unjustly.","Mletaji wa Madhara","Yeye anayeruhusu madhara kwa hekima na haki yake."],
[92,"An-Nafi'","النَّافِعُ","The Bestower of Benefit","The One who brings about good and benefit for His creation.","Mletaji wa Manufaa","Yeye anayeleta wema na manufaa kwa viumbe."],
[93,"An-Nur","النُّورُ","The Light","The One who illuminates the heavens, the earth, and the hearts.","Nuru","Yeye anayeangaza mbingu, ardhi na nyoyo."],
[94,"Al-Hadi","الْهَادِي","The Guide","The One who leads whoever He wills to the right path.","Muongozaji","Yeye anayemwongoza amtakaye kwenye njia iliyonyooka."],
[95,"Al-Badi'","الْبَدِيعُ","The Incomparable Originator","The One who creates in ways without precedent to copy.","Mwasisi Asiye na Mfano","Yeye anayeumba bila kuiga mfano wowote."],
[96,"Al-Baqi","اَلْبَاقِي","The Everlasting","The One whose existence has no end.","Wa Kudumu","Yeye ambaye kuwepo kwake hakuna mwisho."],
[97,"Al-Warith","الْوَارِثُ","The Inheritor","The One who remains when all creation has perished.","Mrithi","Yeye atakayebaki baada ya viumbe vyote kutoweka."],
[98,"Ar-Rashid","الرَّشِيدُ","The Guide to the Right Way","The One who directs all affairs to their proper, wise outcome.","Mwongozaji Sahihi","Yeye anayeelekeza mambo yote kwenye matokeo sahihi na ya hekima."],
[99,"As-Sabur","الصَّبُورُ","The Patient","The One who does not rush to punish those who disobey.","Mvumilivu Mkuu","Yeye asiyeharakisha kuadhibu wanaoasi."],
];

const names = rows.map(([number, transliteration, arabic, enName, enMeaning, swName, swMeaning]) => ({
  number,
  arabic,
  transliteration,
  translations: {
    en: { name: enName, meaning: enMeaning },
    sw: { name: swName, meaning: swMeaning },
  },
  audio: `/audio/asma-ul-husna/${transliteration.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}.mp3`,
}));

const out = `// Auto-generated. 99 Names of Allah (Asma-ul-Husna), bilingual EN/SW.
// Arabic script & transliteration order cross-checked against published references.
// English & Swahili meanings are short original paraphrases for study purposes —
// please review with a knowledgeable teacher/scholar for religious accuracy and nuance,
// especially the Swahili wording, before using this content for formal teaching.
export const namesData = ${JSON.stringify(names, null, 2)};

export const TOTAL_NAMES = ${names.length};
`;

fs.writeFileSync(new URL("../data/names.js", import.meta.url), out);
console.log("Wrote data/names.js with", names.length, "names");
